[pre-commit]
parallel = true

[pre-commit.commands.lint-and-format-biome]
run = "pnpm run fix:biome"
glob = "*.{css,json,ts,mjs}"
stage_fixed = true

[pre-commit.commands.format-prettier]
run = "pnpm run fmt:prettier"
glob = "*.{html,md,yaml,yml}"
stage_fixed = true

[pre-commit.commands.lychee]
run = "lychee -c ./.lychee.toml {staged_files}"
glob = "*.md"
exclude = ["CHANGELOG.md"]
