[pre-commit]
parallel = true

[pre-commit.commands.lint-and-format]
run = "pnpm run fix"
glob = "*.{css,html,json,md,ts,mjs}"
stage_fixed = true

[pre-commit.commands.typos]
run = "typos {staged_files}"
exclude = ["CHANGELOG.md"]
