[pre-commit]
parallel = true

[pre-commit.commands.lint-and-format]
run = "pnpm run fix"
glob = "*.{css,html,json,ts,mjs,md,yaml,yml}"
stage_fixed = true

[pre-commit.commands.lychee]
run = "lychee -c ./.lychee.toml {staged_files}"
glob = "*.md"
exclude = ["CHANGELOG.md"]
