printWidth = 80
tabWidth = 2
useTabs = false
proseWrap = "always"
endOfLine = "lf"

# html only
singleAttributePerLine = false

[[overrides]]
files = ["*.yml", "*.yaml"]
options = { printWidth = 120 }
